--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2024 10:47:36 PM
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS db_todo_app;

CREATE DATABASE IF NOT EXISTS db_todo_app
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE db_todo_app;

--
-- Create table `user`
--
CREATE TABLE IF NOT EXISTS user (
  UserID int NOT NULL AUTO_INCREMENT,
  Username varchar(255) DEFAULT NULL,
  Fullname varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `group`
--
CREATE TABLE IF NOT EXISTS `group` (
  GroupID int NOT NULL AUTO_INCREMENT,
  GroupName varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (GroupID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `user_group`
--
CREATE TABLE IF NOT EXISTS user_group (
  UserID int NOT NULL,
  GroupID int NOT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (UserID, GroupID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE user_group
ADD CONSTRAINT FK_user_group_GroupID FOREIGN KEY (GroupID)
REFERENCES `group` (GroupID);

--
-- Create foreign key
--
ALTER TABLE user_group
ADD CONSTRAINT FK_user_group_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

--
-- Create table `todo`
--
CREATE TABLE IF NOT EXISTS todo (
  TodoID int NOT NULL AUTO_INCREMENT,
  TodoName varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  GroupID int DEFAULT NULL,
  PRIMARY KEY (TodoID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE todo
ADD CONSTRAINT FK_todo_GroupID FOREIGN KEY (GroupID)
REFERENCES `group` (GroupID) ON DELETE CASCADE;

-- 
-- Dumping data for table user
--
-- Table db_todo_app.user does not contain any data (it is empty)

-- 
-- Dumping data for table `group`
--
INSERT INTO `group` VALUES
(1, 'string', '2024-10-13 09:25:37', NULL);

-- 
-- Dumping data for table user_group
--
-- Table db_todo_app.user_group does not contain any data (it is empty)

-- 
-- Dumping data for table todo
--
-- Table db_todo_app.todo does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;