--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/18/2024 10:48:43 PM
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS db_todo_app;

CREATE DATABASE IF NOT EXISTS db_todo_app
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE db_todo_app;

--
-- Create table `user`
--
CREATE TABLE IF NOT EXISTS user (
  UserID int NOT NULL AUTO_INCREMENT,
  Username varchar(255) DEFAULT NULL,
  Fullname varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `group`
--
CREATE TABLE IF NOT EXISTS `group` (
  GroupID int NOT NULL AUTO_INCREMENT,
  GroupName varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (GroupID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `user_group`
--
CREATE TABLE IF NOT EXISTS user_group (
  UserID int NOT NULL,
  GroupID int NOT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (UserID, GroupID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE user_group
ADD CONSTRAINT FK_user_group_GroupID FOREIGN KEY (GroupID)
REFERENCES `group` (GroupID);

--
-- Create foreign key
--
ALTER TABLE user_group
ADD CONSTRAINT FK_user_group_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

--
-- Create table `todo`
--
CREATE TABLE IF NOT EXISTS todo (
  TodoID int NOT NULL AUTO_INCREMENT,
  TodoName varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  GroupID int DEFAULT NULL,
  StartDate datetime DEFAULT NULL,
  EndDate datetime DEFAULT NULL,
  PRIMARY KEY (TodoID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 105,
AVG_ROW_LENGTH = 163,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE todo
ADD CONSTRAINT FK_todo_GroupID FOREIGN KEY (GroupID)
REFERENCES `group` (GroupID) ON DELETE CASCADE;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'string', 'string', '2024-10-16 01:25:04', 'Current user', '2024-10-15 18:24:59', 'string', 'string');

-- 
-- Dumping data for table `group`
--
INSERT INTO `group` VALUES
(1, 'Sửa tên group 1', '2024-10-13 09:25:37', 'a', '2024-10-27 21:54:48', 'Current user'),
(2, 'Quay video', '2024-10-13 18:06:55', 'admin', NULL, NULL),
(6, 'Letha241', '1970-01-01 00:07:13', 'Letha Bolt', '1970-01-01 00:00:04', 'Abraham Acevedo');

-- 
-- Dumping data for table user_group
--
-- Table db_todo_app.user_group does not contain any data (it is empty)

-- 
-- Dumping data for table todo
--
INSERT INTO todo VALUES
(5, 'Conrad1997', '1990-03-24 01:52:33', 'Stevie Frizzell', '1971-11-29 16:56:57', 'Vanita Edmonds', 6, '1983-05-22 11:25:04', '1970-01-01 02:13:43'),
(6, 'Drew9', NULL, NULL, '2003-09-14 08:29:01', 'Kennith Carswell', 6, '1970-01-01 00:00:07', '2018-01-24 01:41:42'),
(7, 'Kim1953', '1982-04-02 05:25:42', 'Jackeline Acker', '2023-04-28 05:07:56', 'Cary Benitez', 6, '1970-01-01 00:00:09', '2021-08-15 06:57:21'),
(8, 'Latonya2022', '1970-01-01 01:19:23', 'Twila Bock', '2003-04-12 07:30:40', 'Kathyrn Beatty', 6, '1970-01-01 00:31:40', '2006-03-24 21:04:12'),
(9, 'Stamm465', '2022-06-12 12:03:42', 'Reina Adkins', '2000-10-31 17:23:27', 'Erasmo Joe', 6, '1970-01-01 00:00:01', '1976-12-13 18:03:30'),
(10, 'Winkler2019', NULL, NULL, '2001-07-30 21:05:08', 'Rodrick Paulsen', 6, '1980-08-28 10:18:34', '1993-07-08 05:13:23'),
(11, 'Brendan547', '1981-10-08 14:06:21', 'Lavonia Whiteside', '1984-01-21 14:54:03', 'Marco Horn', 6, '1989-01-11 15:05:10', '2005-07-06 05:22:17'),
(12, 'Gino2021', '2024-04-01 12:46:45', 'Kendrick Naranjo', '2002-04-28 00:39:34', 'Tanner Butler', 6, '1974-05-14 07:03:13', '1973-01-18 15:34:15'),
(13, 'Abby664', '1973-10-03 12:55:12', 'Kim Desantis', '1970-01-01 00:08:53', 'Carline Mccall', 6, '1986-03-23 21:08:51', '2009-01-03 01:17:08'),
(14, 'Jolene437', '1984-12-07 02:58:19', 'Raul Palma', '1970-01-01 00:04:54', 'Cora Pacheco', 6, '1977-07-23 19:00:15', '2023-05-26 21:08:58'),
(15, 'Alonso441', '2009-09-07 12:08:08', 'Lorette Ortiz', '2022-05-26 09:23:16', 'Cleotilde Gorman', 6, '2009-07-09 05:10:10', '1977-04-27 05:49:48'),
(16, 'Abby754', '2003-02-24 02:18:05', 'Jewel Plummer', '2012-01-03 10:54:58', 'Gus Sawyer', 6, '1971-05-15 23:25:55', '2012-04-13 07:42:52'),
(17, 'Simpson5', NULL, NULL, '1973-05-17 19:32:26', 'Alfonzo Bohn', 6, '2013-07-13 17:47:17', '2000-07-21 01:41:14'),
(18, 'Darius5', '1970-01-01 00:00:07', 'Carter Matlock', NULL, NULL, 6, '2002-03-16 10:18:27', '1970-01-01 00:15:23'),
(19, 'Boling2025', '2018-09-09 23:08:31', 'Clemente Craddock', '1970-01-01 00:00:06', 'Addie Tyner', 6, '2003-12-04 09:24:46', '2008-05-26 07:18:09'),
(20, 'Abbie1953', '1993-04-09 12:12:44', 'Rolland Watson', '1995-05-25 02:27:25', 'Christian Abernathy', 6, '1970-01-01 00:12:43', '2020-08-05 09:44:27'),
(21, 'Bernita1999', '2014-06-02 22:38:46', 'Kayleen Hogg', '1976-08-09 22:31:03', 'Tory Olson', 6, '2011-04-16 22:47:38', '1979-12-22 15:24:50'),
(22, 'Deborah2002', '1970-06-18 08:37:16', 'Loise Mayers', '1970-01-01 00:08:32', 'Amiee Pond', 6, '1970-01-01 00:00:03', '1981-01-08 20:42:02'),
(23, 'Earl2024', '2012-06-28 09:40:18', 'Marine Turley', '1970-01-01 02:05:18', 'Glynis Battle', 6, '1970-09-28 01:39:12', '1999-12-01 20:58:39'),
(24, 'Constance1951', '2015-07-01 02:59:52', 'Debby Concepcion', '1999-07-29 02:37:50', 'Joeann Garcia', 6, '2018-12-21 04:48:29', '2004-05-28 16:06:35'),
(25, 'Shon1986', '1970-01-01 01:00:32', 'Kent Staton', '1974-03-05 02:16:12', 'Jeffry Pease', 6, '1980-05-07 18:27:42', NULL),
(26, 'Justin1958', '2018-04-09 14:06:34', 'Emmett Moulton', '2010-11-06 16:33:55', 'Nerissa Word', 6, '1970-01-01 00:00:05', '2005-01-04 08:05:35'),
(27, 'Williams7', '2006-06-20 10:21:58', 'Clarinda Acker', '1996-08-31 19:48:11', 'Freeda Brinkley', 6, '1970-01-01 00:00:02', '2012-04-02 00:20:13'),
(28, 'Cathy1961', '1993-10-27 03:46:43', 'Darrick Cardoza', '1979-12-07 18:28:14', 'Stevie Durham', 6, '1986-12-28 19:52:40', '1982-12-21 20:45:03'),
(29, 'Rocky1969', NULL, NULL, '2007-10-19 23:25:40', 'Joshua Villasenor', 6, NULL, '2017-05-28 21:40:36'),
(30, 'Adaline2010', NULL, NULL, '1994-07-12 05:18:34', 'Federico Lujan', 6, '1981-06-30 11:30:06', '2009-11-08 00:51:37'),
(31, 'Drew35', '1982-03-04 17:29:28', 'Kecia Adcock', '1970-01-01 02:03:38', 'Emmett Musgrove', 6, '2011-01-20 06:20:46', '1979-09-29 03:33:10'),
(32, 'Ray2015', '1985-03-15 09:11:04', 'Maurice Mireles', '1986-02-26 04:40:13', 'Akiko Lester', 6, '1970-01-01 00:14:48', '2002-05-27 20:40:31'),
(33, 'Arvilla9', '1970-01-01 00:14:28', 'Ruben Simpson', '2020-07-12 06:52:48', 'Cassi Atkinson', 6, '1970-01-01 00:00:02', '1977-12-23 21:54:40'),
(34, 'Bourgeois2010', '1970-01-01 00:00:07', 'Britt Malley', '1970-01-01 00:00:04', 'Kevin Kim', 6, '1970-01-01 00:09:08', '2021-02-12 22:54:57'),
(35, 'Ron2016', '1993-06-14 16:41:52', 'Jamie Creech', '2023-11-19 03:17:44', 'Bennie Broussard', 6, '2000-08-26 04:34:10', '2007-10-06 08:55:31'),
(36, 'Ada2007', '1981-07-05 10:57:03', 'Luis Cruse', '1984-08-17 15:15:38', 'Tess Townsend', 6, '1976-08-13 18:10:27', '2012-05-09 06:38:28'),
(37, 'Clelia1967', '2001-01-05 12:27:01', 'Carol Abrams', '1980-09-26 20:09:45', 'Carl Switzer', 6, '1971-12-23 13:22:46', '2022-06-22 17:08:31'),
(38, 'Dillon2027', '2012-02-01 20:21:36', 'Adah Adair', NULL, NULL, 6, '1970-01-01 00:08:45', '1975-06-09 15:46:33'),
(39, 'Washington5', '1970-01-01 00:00:12', 'Henry Crump', '1997-02-03 18:41:00', 'Alysa Harrell', 6, '1999-10-15 19:37:46', '1970-01-01 00:02:56'),
(40, 'Packard2000', '1993-11-23 15:45:33', 'Magdalena Ogle', '1970-01-01 00:09:09', 'Olga Haag', 6, '1970-01-01 00:00:54', '2020-12-05 10:49:50'),
(41, 'Bonilla2029', '2005-01-25 03:31:24', 'Donovan Allison', '1970-01-01 01:37:34', 'Dia Casteel', 6, '1970-01-01 00:14:52', '1970-01-01 00:23:34'),
(42, 'Abbie2021', '1972-02-13 08:38:28', 'Jeremy Aranda', '1970-01-01 02:37:34', 'Adam Thames', 6, '2016-03-26 15:45:34', '2023-11-25 10:29:35'),
(43, 'Charla71', '1981-03-21 18:20:25', 'Camie Burch', '1971-03-17 13:48:35', 'Bridgette Conley', 6, '1970-01-01 00:00:07', '1970-05-18 18:31:48'),
(44, 'Cher425', '2022-01-17 11:44:02', 'Robbie Canty', '2011-09-29 13:58:08', 'Rodger Crawford', 6, '2011-04-16 02:31:05', '1972-12-28 10:24:15'),
(45, 'Adah2028', '1970-01-01 00:14:57', 'Lavone Amos', '2015-09-13 05:00:50', 'Adaline Ashley', 6, '1970-01-01 00:01:38', '1977-03-06 10:00:58'),
(46, 'Mosby661', '1993-01-10 04:09:59', 'Johnnie Allard', '2015-04-29 19:15:52', 'Cody Feliciano', 6, NULL, '2007-10-27 12:45:28'),
(47, 'Hunter2027', '1980-11-24 05:34:14', 'Debbra Acuna', '1970-01-01 02:04:26', 'Everette Anders', 6, '1974-08-07 12:58:20', '1973-01-07 00:06:04'),
(48, 'Anglin1953', '1970-11-30 17:15:51', 'Abdul Bergstrom', '1975-03-22 06:44:42', 'Abby Marcum', 6, '2012-08-20 20:39:54', NULL),
(49, 'Albert381', NULL, NULL, '1971-10-01 19:57:04', 'Marylyn Medina', 6, '1970-01-01 00:08:52', '2018-05-24 21:04:35'),
(50, 'Ordonez879', '1982-11-16 13:47:31', 'Nathanael Medina', '2018-09-11 21:55:14', 'Tim Howe', 6, '1997-11-03 05:48:00', '1970-01-01 00:03:47'),
(51, 'Burrell393', '1996-11-12 03:49:20', 'Kasey Savoy', '2023-10-14 19:46:59', 'Toney Paradis', 6, '2010-01-28 17:47:23', '2004-12-16 20:19:20'),
(52, 'Athena521', '1970-01-01 00:01:02', 'Raphael Beckman', '1970-05-07 12:25:50', 'Hilma Bower', 6, '1991-10-25 22:48:12', '1970-01-01 00:00:08'),
(53, 'Alonzo218', '2015-10-31 10:51:49', 'Eugenia Johansen', '2019-01-15 14:34:04', 'Sanford Abbott', 6, NULL, NULL),
(54, 'Nieto1959', '1993-01-13 22:16:41', 'Merissa Minter', '1970-01-01 00:00:44', 'Minh Withers', 6, '1970-01-01 00:05:05', '1970-01-01 00:07:49'),
(55, 'Harlan2015', '1993-05-26 12:13:02', 'Alejandro Norwood', '1997-04-01 00:03:14', 'Eldridge Cornett', 6, '2018-04-08 07:14:28', '1970-01-01 00:00:07'),
(56, 'Tory1958', '2022-02-22 23:35:27', 'Enoch Dortch', '1989-06-26 14:11:51', 'Louie Freedman', 6, '2011-11-01 15:50:51', '1970-01-01 00:01:36'),
(57, 'Adalberto2008', '1972-06-09 17:28:21', 'Kathleen Burnside', '2014-07-04 03:21:56', 'Adolph Braxton', 6, '2020-08-24 11:00:22', '2020-03-27 20:07:58'),
(58, 'Needham1951', '1977-05-19 10:27:52', 'Stevie Vallejo', '1999-07-06 05:21:19', 'Adela Chan', 6, '2023-06-04 22:15:55', NULL),
(59, 'Darius1967', '1993-04-10 14:04:40', 'Gilda Abney', NULL, NULL, 6, '1989-03-15 06:04:53', '1970-01-01 00:59:28'),
(60, 'Acker2021', '2016-01-18 02:48:51', 'Pearlene Starnes', '1970-01-01 00:16:16', 'Chaya Amador', 6, '1970-01-01 00:00:39', '1989-07-31 23:30:53'),
(61, 'Mattson2000', '2004-11-26 23:38:04', 'Kelley Hiatt', '2015-01-04 23:10:40', 'Trudy Ferry', 6, '1996-10-24 00:54:14', '1970-01-01 01:21:14'),
(62, 'Elvie139', '1970-01-01 00:00:47', 'Brady Street', '1970-01-01 00:00:02', 'Aline Carlos', 6, '2000-08-05 20:23:09', '1981-02-22 00:35:35'),
(63, 'Diggs44', '1999-03-17 04:59:19', 'Beau Poston', '1970-01-01 00:15:57', 'Denyse Ma', 6, '2007-12-12 04:49:15', '1970-01-01 00:30:52'),
(64, 'Mccutcheon1967', '1973-11-11 07:30:57', 'Christeen Oconnor', '2004-06-23 17:29:48', 'Elliot Paterson', 6, '1980-11-14 05:36:41', '2018-07-05 16:17:36'),
(65, 'Collins23', '2024-04-18 15:53:46', 'Aleisha Story', '1999-08-12 05:14:42', 'Maria Anthony', 6, '1970-01-01 00:20:07', '2011-07-25 00:19:43'),
(66, 'Jimmie835', '1985-07-30 06:40:30', 'Greta Prosser', '2022-05-26 05:15:45', 'Carmine Newell', 6, '2010-04-26 03:24:58', '1970-01-01 00:00:07'),
(67, 'Kareen1', '1989-10-10 07:00:28', 'Shawn Deaton', '1982-10-06 06:06:55', 'Julio Gillis', 6, '1984-03-04 09:01:28', '1970-01-01 00:01:06'),
(68, 'Lefebvre9', '1971-04-30 15:58:44', 'Ada Rapp', '2010-02-14 07:26:44', 'Michel Beale', 6, '1970-01-01 02:08:04', '1995-02-19 10:36:42'),
(69, 'Ambrose9', '2007-04-18 04:04:16', 'Abe Christie', '2019-06-13 16:14:48', 'Annemarie Hammer', 6, '1970-01-01 01:12:19', '1973-06-09 04:45:43'),
(70, 'Orlando1962', '1972-05-16 06:43:04', 'Abbie Bullard', '1970-01-01 00:01:24', 'Samual Sheffield', 6, '2006-02-17 22:40:48', '1978-07-26 15:36:19'),
(71, 'Myron77', '1978-09-11 03:00:35', 'Jenny Schulze', '2020-10-19 20:50:21', 'Marni Woodson', 6, '1999-01-27 15:53:30', '1982-02-01 05:07:59'),
(72, 'Scott4', '1970-01-01 00:00:12', 'Jamel Washington', '1993-02-20 10:27:44', 'Debroah Lombard', 6, '1986-11-12 12:51:13', '1970-01-01 00:00:02'),
(73, 'Abby789', '1981-05-09 21:45:37', 'Augustus Barnette', '1989-05-05 19:48:07', 'Teena Mintz', 6, '1970-01-01 00:01:38', '2011-11-20 04:32:12'),
(74, 'Shapiro1998', '1970-01-01 00:01:29', 'Rick Trevino', '1974-05-17 12:05:48', 'Gerry Hutchens', 6, '1991-08-19 06:40:37', '1970-01-01 00:05:18'),
(75, 'Doyle1966', '1976-08-03 11:39:59', 'Azalee Wang', '1989-04-25 06:36:26', 'Adeline Levesque', 6, '1980-04-17 19:48:17', '1999-05-27 06:44:54'),
(76, 'Les1989', '1970-01-01 00:15:45', 'Jackqueline Abraham', '1970-01-01 00:00:03', 'Iesha Jimenez', 6, '1999-03-03 19:42:12', NULL),
(77, 'Blum2012', '1993-09-15 18:40:07', 'Marcel Casas', '1970-01-01 00:01:09', 'Delorse Mayes', 6, '1970-01-01 00:09:31', '1984-01-29 01:24:32'),
(78, 'Odelia1973', '1992-11-08 03:15:54', 'Chiquita Headrick', '2005-07-05 12:40:08', 'Myrl Combs', 6, '1970-01-01 00:00:01', '1970-01-01 00:01:25'),
(79, 'Phipps1990', '1983-02-17 08:33:21', 'Mitchell Tanner', '1998-08-25 15:29:34', 'Alonzo Agee', 6, '1993-01-13 00:02:30', '1970-01-01 00:00:04'),
(80, 'Alfreda2016', '1984-08-07 19:06:09', 'Miesha Goldsmith', '1992-05-20 09:53:13', 'Janell Beale', 6, '2021-10-06 01:25:48', '1970-01-01 00:02:24'),
(81, 'Matt1971', '1981-09-26 05:31:54', 'Ahmed Abernathy', NULL, NULL, 6, '2001-08-23 16:08:54', '2007-09-03 17:39:39'),
(82, 'Phylis6', '1984-01-04 17:39:21', 'Eddy Snodgrass', '1989-02-17 03:13:58', 'Tawny Lister', 6, '1972-08-05 00:25:37', '1970-01-01 00:01:00'),
(83, 'Abram91', '1977-02-12 01:35:29', 'Herschel Allison', '1970-01-01 00:35:58', 'Denita Teal', 6, NULL, '1982-04-21 11:03:38'),
(84, 'Bragg8', NULL, NULL, '2002-12-15 05:19:38', 'Eugene Valadez', 6, '1970-01-01 00:00:01', '2011-12-01 06:52:11'),
(85, 'Oneida9', '1993-05-29 19:28:46', 'Carmelita Abel', '2017-03-19 21:49:37', 'Jeanette Friedman', 6, '2020-06-11 10:32:24', '2009-10-17 06:04:26'),
(86, 'Ferris962', '1972-04-11 20:52:44', 'Daron Lowery', '1992-02-11 18:37:59', 'Columbus Ackerman', 6, '1985-10-09 17:07:55', '1994-05-31 20:25:14'),
(87, 'Siler993', '1970-01-01 00:00:10', 'Rudolph Staley', '1999-07-26 12:40:19', 'Irwin Archibald', 6, '1974-01-14 16:32:53', '1997-05-05 13:26:23'),
(88, 'Genna31', '2023-12-26 14:54:00', 'Seth Martin', NULL, NULL, 6, '2003-08-18 02:51:02', '1988-11-11 09:15:37'),
(89, 'Clay1991', '2003-12-02 18:35:22', 'Theola Addison', '2004-10-23 20:38:57', 'Sidney Hennessey', 6, '1970-01-01 00:01:40', '2022-05-25 19:42:52'),
(90, 'Travis2021', '2001-05-14 11:17:25', 'Isela Crittenden', '1996-07-17 07:44:45', 'Eloy Negron', 6, '1970-01-01 00:00:02', '1970-01-01 00:03:03'),
(91, 'Carl172', '1983-02-26 19:51:28', 'Marvella Langston', '2011-06-03 18:34:57', 'Lara Moran', 6, '2023-11-02 21:08:21', NULL),
(92, 'Fowler1982', '2008-03-09 23:04:09', 'Cassondra Quintana', NULL, NULL, 6, '1993-10-13 16:04:55', '1970-01-01 00:02:27'),
(93, 'Darcie1963', '2008-01-31 22:45:41', 'Ada Barron', '1985-07-07 21:39:06', 'Hung Ackerman', 6, '1970-01-01 00:16:29', '2018-05-09 18:05:05'),
(94, 'Valerie715', '1999-08-24 00:32:31', 'Bob Whitlow', '1970-01-01 00:00:45', 'Johnson Adair', 6, '2019-08-21 13:17:46', '1970-01-01 00:00:04'),
(95, 'Alston1967', '1975-10-21 03:38:59', 'Aileen Ricks', '1995-08-26 23:01:14', 'Beverlee Aponte', 6, '1972-05-19 17:11:13', '2005-05-16 19:48:23'),
(96, 'Fountain877', '1970-01-01 00:50:37', 'Carter Wilburn', '1992-01-03 11:57:56', 'Bula Andrews', 6, '1970-01-01 00:06:04', '2005-11-06 08:23:12'),
(97, 'Owen181', NULL, NULL, '2001-03-31 13:56:04', 'Ambrose Nieto', 6, '1978-04-02 20:26:32', '1970-01-01 00:00:06'),
(98, 'Adam4', '1970-01-01 00:00:10', 'Lewis Kurtz', '1970-01-01 00:06:47', 'Tasha Gallagher', 6, '2018-04-29 11:19:05', '1974-06-19 02:34:57'),
(99, 'Davidson9', '1970-01-01 00:27:32', 'Martin Carpenter', '1995-09-11 13:36:49', 'Hwa Beckman', 6, NULL, '2008-03-14 16:06:54'),
(100, 'Mandi293', NULL, NULL, '1979-06-06 05:52:20', 'Norine Mackey', 6, NULL, NULL),
(101, 'Tristan98', '1975-05-04 22:36:19', 'Maynard Mullins', NULL, NULL, 6, NULL, '1972-10-02 10:53:28'),
(102, 'Stacy2011', '1986-12-14 01:23:37', 'Deena Seifert', NULL, NULL, 6, NULL, NULL),
(103, 'Bragg72', '1976-11-11 10:45:50', 'Sonny Epps', NULL, NULL, 6, NULL, NULL),
(104, 'Newton2009', NULL, NULL, NULL, NULL, 6, NULL, NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;